### ISSUE TITLE
after upgrade from jetcd 0.8.5 to 0.8.6 - java.lang.NoClassDefFoundError: io/netty/channel/MultiThreadIoEventLoopGroup

### ISSUE THREAD

**Issue by jarekchr** [etcd-io/jetcd#1542]
**Versions**
- etcd: 3.6.5 (this is not important at this moment)
- jetcd: 0.8.6
- java: 21/17

**Describe the bug**
After upgrade to jetcd 0.8.6 my tests throw exception:
java.lang.NoClassDefFoundError: io/netty/channel/MultiThreadIoEventLoopGroup

Error Message

io/netty/channel/MultiThreadIoEventLoopGroup

Stacktrace

java.lang.NoClassDefFoundError: io/netty/channel/MultiThreadIoEventLoopGroup
	at io.vertx.core.spi.transport.Transport.eventLoopGroup(Transport.java:93)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:214)
	at io.vertx.core.impl.VertxBootstrapImpl.instantiateVertx(VertxBootstrapImpl.java:231)
	at io.vertx.core.impl.VertxBootstrapImpl.vertx(VertxBootstrapImpl.java:247)
	at io.vertx.core.Vertx$1.build(Vertx.java:131)
	at io.vertx.core.Vertx.vertx(Vertx.java:159)
	at io.etcd.jetcd.impl.ClientConnectionManager.vertx(ClientConnectionManager.java:227)
	at io.etcd.jetcd.impl.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:162)
	at io.etcd.jetcd.impl.ClientConnectionManager.defaultChannelBuilder(ClientConnectionManager.java:153)
	at io.etcd.jetcd.impl.ClientConnectionManager.getChannel(ClientConnectionManager.java:74)
	at io.etcd.jetcd.impl.ClientConnectionManager.newStub(ClientConnectionManager.java:106)
	at io.etcd.jetcd.impl.KVImpl.<init>(KVImpl.java:52)
	at io.etcd.jetcd.impl.ClientImpl.lambda$new$0(ClientImpl.java:48)
	at io.etcd.jetcd.support.MemorizingClientSupplier.get(MemorizingClientSupplier.java:37)
	at io.etcd.jetcd.impl.ClientImpl.getKVClient(ClientImpl.java:65)
[...]

**To Reproduce**

**Expected behavior**

**Additional context**
I think that this is caused by use of new vertx.

**Comment by lburgazzoli** [comment]
do you have any direct or indirect netty dependencies?

**Comment by jarekchr** [comment]
yes, in pom.xml we're forcing netty 4.1.128.Final:
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.128.Final</version>
        </dependency>

**Comment by lburgazzoli** [comment]
That could be a problem, yes. can't you upgrade/downgrade ?

**Comment by jarekchr** [comment]
No - too many CVEs in previous versions of netty.
Actually this jetcd version updates indirect dependency of 2 new CVEs (CVE-2025-11965  and CVE-2025-11966) in vertx (1x high, 1x medium) that I hoped to be removed but it doesn't work.
I don't remember now exact issue but we also checked some time ago that with netty 4.2.x it doesn't work so we have to stay for a moment on 4.1.x.

**Comment by evilin13** [comment]
Thanks for the prompt response, @jarekchr !

**Comment by cbornet** [comment]
The problem comes from https://github.com/etcd-io/jetcd/pull/1483 which bumped vertx version from 4.x to 5.x.
Vertx 4 works with Netty 4.2 and Vertx 5 with Netty 4.1.
That's in conflict with grpc which is based on Netty 4.1.
I think it's safe to downgrade Vertx to 4.x since the version updates were only dependabot ones without API call changes.

**Comment by cbornet** [comment]
The problem is that Dependabot upgraded Vertx from 4.x to 5.x in https://github.com/etcd-io/jetcd/pull/1483
And Vertx 5 works with Netty 4.2.
This is in conflict with grpc-java which is still on Netty 4.1 
And with users using Netty 4.1 in their project (still a lot)
We can't just downgrade Vertx in users setup as jetcd has generated stubs that are incompatible between Vertx 5 and 4.

**Comment by cbornet** [comment]
@lburgazzoli would you accept a PR to downgrade Vertx to 4.x and to align the Netty versions ? (Vertx 4.5 is still maintained)
